/* ============================================================
   CHECKLIST-DATA.JS
   ============================================================ */
const CHECKLIST = {
    inclusion: [
        { id: 'incl_reunions_concernees', label: 'Des personnes concernees (handicapees) ont ete invitees a participer a la preparation de l\'evenement', pourquoi: 'Rien sur nous sans nous. Les concerneEs sont les expertes de leur propre experience.', sections: ['tous'] },
        { id: 'incl_besoins_collectes', label: 'Un canal a ete ouvert pour recueillir les besoins des participant·es avant l\'evenement', pourquoi: 'Permettre aux gens de signaler leurs besoins en amont permet de s\'y preparer.', sections: ['tous'] },
        { id: 'incl_benevoles_formes', label: 'Les benevoles d\'accompagnement ont ete forme·es (gestes, communication, respect de l\'autonomie)', pourquoi: 'Un accompagnement mal calibre peut etre aussi excluant que l\'absence d\'accompagnement.', sections: ['tous'] },
        { id: 'incl_referente_identifiee', label: 'Une personne referente accessibilite a ete identifiee et sera joignable le jour J', pourquoi: 'Les participant·es doivent pouvoir s\'adresser a quelqu\'un de precis en cas de besoin.', sections: ['tous'] },
        { id: 'incl_programme_partage', label: 'Le programme complet (horaires, lieux, contenu) a ete partage en avance avec les participant·es qui en ont besoin', pourquoi: 'Essentiel pour les personnes neurodivergentes et celles qui ont besoin d\'anticiper.', sections: ['tous'] },
        { id: 'incl_changements_signales', label: 'Un protocole existe pour prevenir rapidement en cas de changement de derniere minute', pourquoi: 'Un changement inattendu peut empecher certaines personnes de participer ou declencher une grande anxiete.', sections: ['tous'] },
    ],
    lieu: [
        { id: 'lieu_acces_plain_pied', label: 'Acces de plain-pied ou rampe d\'acces fonctionnelle', pourquoi: 'Indispensable pour les fauteuils, deambulateurs et toutes les aides a la mobilite.', sections: ['lieu'] },
        { id: 'lieu_ascenseur', label: 'Ascenseur disponible si l\'espace est sur plusieurs niveaux (et en etat de fonctionnement)', pourquoi: 'Un ascenseur en panne le jour J est aussi problematique que l\'absence d\'ascenseur. Verifier la veille.', sections: ['lieu'] },
        { id: 'lieu_toilettes_ufr', label: 'Toilettes adaptees aux UFR (cabine spacieuse, barre d\'appui, hauteur adaptee)', pourquoi: 'L\'absence de toilettes adaptees est une raison valable de ne pas venir. On dit UFR et non PMR, terme reducteur.', sections: ['lieu'] },
        { id: 'lieu_chaises', label: 'Chaises et assises disponibles en nombre suffisant, accessibles sans effort', pourquoi: 'Pour les personnes qui ne peuvent pas rester debout longtemps.', sections: ['non_tractage'] },
        { id: 'lieu_espace_circulation', label: 'Espace suffisant pour circuler en fauteuil (90 cm minimum entre les obstacles)', pourquoi: 'En dessous de 80 cm, le passage devient impossible pour beaucoup de fauteuils.', sections: ['lieu'] },
        { id: 'lieu_portes', label: 'Portes legeres ou avec systeme d\'ouverture automatique', pourquoi: 'Les portes lourdes sont un obstacle majeur pour les personnes en fauteuil ou avec peu de force dans les bras.', sections: ['lieu'] },
        { id: 'lieu_accueil_entree', label: 'L\'accueil des participant·es est situe a proximite immediate de l\'entree principale', pourquoi: 'Chercher l\'accueil apres une longue marche est epuisant et desorientant.', sections: ['lieu'] },
        { id: 'lieu_flechage', label: 'Flechage clair depuis l\'entree : grands caracteres, bon contraste, pictogrammes', pourquoi: 'Pour les personnes malvoyantes, cognitives ou anxieuses, s\'orienter sans signaletique est tres difficile.', sections: ['lieu'] },
        { id: 'lieu_recharge', label: 'Des prises electriques accessibles sont disponibles pour recharger fauteuils electriques et autres appareillages', pourquoi: 'Pour les fauteuils electriques, implants cochleaires et autres appareils : une batterie a plat peut forcer quelqu\'un a partir prematurement.', sections: ['lieu'] },
        { id: 'lieu_parking', label: 'Stationnement accessible a proximite immediate (places GIC/GIG signalees)', pourquoi: 'Un parking trop eloigne peut etre redhibitoire pour certaines personnes.', sections: ['lieu'] },
        { id: 'lieu_vestiaire', label: 'Vestiaire accessible (si vestiaire il y a)', pourquoi: 'Le vestiaire doit etre accessible sans marches ni portes lourdes.', sections: ['grand'] },
        { id: 'lieu_caillebotis', label: 'Caillebotis poses sur les axes de circulation en exterieur (pelouse, terre)', pourquoi: 'Sur une pelouse ou de la terre, un fauteuil s\'enfonce immediatement.', sections: ['grand'] },
        { id: 'lieu_logements', label: 'Des logements accessibles sont disponibles en nombre suffisant a proximite', pourquoi: 'Pour les evenements de plusieurs jours : verifier que les hebergements proposes ont des chambres reellement accessibles.', sections: ['grand'] },
        { id: 'lieu_navettes', label: 'Des navettes accessibles (fauteuils) sont prevues entre les logements et le lieu', pourquoi: 'Un transport inaccessible entre le logement et le lieu annule tous les efforts d\'accessibilite sur place.', sections: ['grand'] },
        { id: 'lieu_chiens', label: 'Chiens guides et chiens d\'assistance acceptes dans tous les espaces', pourquoi: 'Un chien d\'assistance est un appareillage medical, pas un animal de compagnie. Leur refus est illegal.', sections: ['tous'] },
        { id: 'lieu_accompagnants', label: 'Gratuite ou tarif reduit pour les accompagnant·es (professionnel·les ou benevoles)', pourquoi: 'Faire payer l\'accompagnant·e revient a faire payer deux fois la personne handicapee.', sections: ['non_tractage'] },
    ],
    cheminement: [
        { id: 'chem_sol_type', label: 'Nature du sol renseignee (bitume, paves, terre, herbe, mixte...)', pourquoi: 'Paves ou gravier : souvent infranchissable en fauteuil.', sections: ['tous'] },
        { id: 'chem_sol_etat', label: 'Etat du sol verifie (fissures, trous, revetement instable)', pourquoi: 'Un sol degrade est un risque de chute et peut bloquer un fauteuil.', sections: ['tous'] },
        { id: 'chem_largeur', label: 'Largeur du passage libre verifiee (90 cm minimum recommande)', pourquoi: 'En dessous de 80 cm, le passage est impossible pour de nombreux fauteuils.', sections: ['tous'] },
        { id: 'chem_pente', label: 'Pente du parcours verifiee et indiquee', pourquoi: 'Une pente forte est difficile voire dangereuse en fauteuil, surtout electrique.', sections: ['tous'] },
        { id: 'chem_marches', label: 'Marches et obstacles ponctuels identifies et decrits', pourquoi: 'Meme une seule marche peut bloquer un fauteuil ou un deambulateur.', sections: ['tous'] },
        { id: 'chem_trottoirs', label: 'Trottoirs en bon etat, bords abaisses aux traversees', pourquoi: 'Un bord de trottoir non abaisse oblige a un detour parfois long.', sections: ['tous'] },
        { id: 'chem_eclairage', label: 'Eclairage suffisant sur le parcours (soir ou lieu sombre)', pourquoi: 'Pour les personnes malvoyantes et pour la securite de toutes.', sections: ['tous'] },
        { id: 'chem_tc', label: 'Arrets de transports en commun accessibles a proximite (lignes, distance)', pourquoi: 'Indiquer precisement la ligne et la distance depuis l\'arret aide a planifier le trajet.', sections: ['tous'] },
    ],
    sensoriel: [
        { id: 'sens_luminosite', label: 'Luminosite du lieu verifiee et indiquee (neons, lumiere naturelle, reglable)', pourquoi: 'Les neons clignotants peuvent declencher des crises pour les personnes epileptiques.', sections: ['non_tractage'] },
        { id: 'sens_volume', label: 'Niveau sonore previsible indique (calme, modere, tres bruyant)', pourquoi: 'Pour les personnes hyperacousiques, un environnement tres bruyant peut etre physiquement douloureux.', sections: ['tous'] },
        { id: 'sens_espace_calme', label: 'Un espace calme est disponible (salle de repos, zone de decompression)', pourquoi: 'Permet aux personnes neurodivergentes ou anxieuses de se ressourcer sans quitter l\'evenement.', sections: ['non_tractage'] },
        { id: 'sens_stroboscopes', label: 'Stroboscopes et lumieres clignotantes : presence signalee clairement dans l\'annonce', pourquoi: 'Pour les personnes epileptiques photosensibles, c\'est une information vitale.', sections: ['non_tractage'] },
        { id: 'sens_boucles', label: 'Boucles magnetiques disponibles (pour les personnes appareillees)', pourquoi: 'Permettent aux personnes avec protheses auditives (programme T) d\'entendre clairement la sono.', sections: ['non_tractage'] },
        { id: 'sens_casques', label: 'Casques anti-bruit disponibles a preter', pourquoi: 'Pour les personnes autistes, hyperacousiques ou anxieuses : reduit la surcharge sensorielle.', sections: ['non_tractage'] },
        { id: 'sens_parfums', label: 'Demande faite aux participant·es d\'eviter les parfums et produits chimiques forts', pourquoi: 'Pour les personnes chimico-sensibles, un parfum fort peut declencher une crise.', sections: ['tous'] },
        { id: 'sens_produits_entretien', label: 'Produits d\'entretien sans parfums chimiques forts utilises dans le lieu', pourquoi: 'Les produits menagers parfumes peuvent rendre un lieu inaccessible pour les personnes chimico-sensibles.', sections: ['lieu'] },
    ],
    communication: [
        { id: 'com_lsf', label: 'Interpretation LSF prevue', pourquoi: 'La LSF est une langue a part entiere. Ne pas la prevoir exclut une partie de la communaute sourde.', sections: ['non_tractage'] },
        { id: 'com_velotypie', label: 'Velotypie (transcription ecrite en direct) prevue', pourquoi: 'Pour les personnes sourdes qui ne signent pas, ou malentendantes.', sections: ['non_tractage'] },
        { id: 'com_soustitres', label: 'Sous-titres pour toutes les videos diffusees', pourquoi: 'Indispensable pour les personnes sourdes et malentendantes.', sections: ['non_tractage'] },
        { id: 'com_micro', label: 'Microphone disponible pour toutes les prises de parole', pourquoi: 'Sans micro, une voix faible ou lointaine est inaudible pour beaucoup.', sections: ['non_tractage'] },
        { id: 'com_falc', label: 'Documents cles disponibles en FALC (Facile a Lire et a Comprendre)', pourquoi: 'Pour les personnes ayant des difficultes de lecture ou de comprehension.', sections: ['non_tractage'] },
        { id: 'com_braille', label: 'Version braille des documents disponible sur demande', pourquoi: 'Pour les personnes aveugles qui lisent en braille.', sections: ['grand'] },
        { id: 'com_audiodesc', label: 'Audiodescription disponible pour les supports visuels', pourquoi: 'Pour les personnes aveugles ou malvoyantes.', sections: ['non_tractage'] },
        { id: 'com_masques_transp', label: 'Masques transparents disponibles pour les benevoles et intervenant·es', pourquoi: 'Pour les personnes sourdes ou malentendantes qui lisent sur les levres.', sections: ['tous'] },
        { id: 'com_pictogrammes', label: 'Pictogrammes de signaletique dans le lieu (toilettes, sorties, accueil...)', pourquoi: 'Pour les personnes ne lisant pas bien le francais, ou a deficience cognitive.', sections: ['lieu'] },
    ],
    sante: [
        { id: 'sante_masques_recommandes', label: 'Port du masque fortement recommande, notamment a moins d\'un metre (personnes immunodeprimees)', pourquoi: 'Beaucoup de personnes handicapees sont immunodeprimees. Formuler comme "fortement recommande" envoie un signal clair.', sections: ['tous'] },
        { id: 'sante_masques_fournis', label: 'Masques fournis sur place pour celles et ceux qui n\'en ont pas', pourquoi: 'Lever la barriere pour celles et ceux qui auraient oublie ou qui n\'en ont pas.', sections: ['tous'] },
        { id: 'sante_aeration', label: 'Aeration reguliere du lieu assuree (fenetres ouvertes, ventilation)', pourquoi: 'Reduit le risque de transmission des virus respiratoires.', sections: ['lieu'] },
        { id: 'sante_fumeurs', label: 'Espace fumeurs strictement separe du groupe principal', pourquoi: 'La fumee de tabac est tres problematique pour les personnes asthmatiques et chimico-sensibles.', sections: ['tous'] },
        { id: 'sante_protocrise', label: 'Protocole en cas de crise (malaise, crise d\'angoisse, meltdown) : qui appeler, ou aller', pourquoi: 'Savoir quoi faire en cas de crise permet d\'agir rapidement et sans paniquer.', sections: ['tous'] },
        { id: 'sante_trigger', label: 'Avertissement de contenu sensible (trigger warning) prevu si necessaire', pourquoi: 'Permet aux personnes concernees de se preparer ou de decider de ne pas assister a une partie.', sections: ['non_tractage'] },
    ],
    alimentation: [
        { id: 'alim_allergenes', label: 'Composition des aliments et allergenes indiques clairement', pourquoi: 'Pour les personnes allergiques, une allergie alimentaire peut etre mortelle.', sections: ['non_tractage'] },
        { id: 'alim_pailles', label: 'Pailles disponibles', pourquoi: 'Pour les personnes ayant des difficultes motrices a porter un verre.', sections: ['non_tractage'] },
    ],
    manif: [
        { id: 'manif_parcours_verifie', label: 'Le parcours complet a ete verifie a pied (sol, largeur, obstacles, pente)', pourquoi: 'Un parcours non verifie peut reserver de mauvaises surprises le jour J.', sections: ['manif'] },
        { id: 'manif_depart_accessible', label: 'Le point de depart est accessible (trottoir abaisse, sol praticable, espace suffisant)', pourquoi: 'Si le point de depart est inaccessible, les personnes en fauteuil ne peuvent pas rejoindre le cortege.', sections: ['manif'] },
        { id: 'manif_cohorte', label: 'Une cohorte de benevoles forme·es est dediee a l\'accompagnement accessibilite dans le cortege', pourquoi: 'Accompagner sans avoir ete forme·e peut etre intrusif ou maladroit.', sections: ['manif'] },
        { id: 'manif_pauses', label: 'Des pauses regulieres sont prevues a des points identifies (frequence et lieux definis)', pourquoi: 'Pour les personnes fatiguees rapidement, les pauses permettent de tenir sur la duree.', sections: ['manif'] },
        { id: 'manif_points_sortie', label: 'Des points de sortie du cortege sont identifies sur le parcours', pourquoi: 'Permettre de quitter le cortege a tout moment sans etre bloque.', sections: ['manif'] },
        { id: 'manif_rythme', label: 'Un rythme lent est maintenu (adapte aux fauteuils et personnes a mobilite reduite)', pourquoi: 'Un cortege rapide laisse rapidement les personnes a mobilite reduite derriere.', sections: ['manif'] },
        { id: 'manif_sono', label: 'La sono / le megaphone est positionne·e de facon a etre audible depuis l\'ensemble du cortege', pourquoi: 'Y compris depuis la partie arriere ou se situent souvent les personnes les plus lentes.', sections: ['manif'] },
        { id: 'manif_lsf_visible', label: 'L\'interprete LSF est positionne·e de facon visible depuis le cortege', pourquoi: 'Si l\'interprete n\'est pas visible, l\'interpretation ne sert a rien.', sections: ['manif'] },
        { id: 'manif_zone_calme', label: 'Une zone ou position calme est prevue dans ou en marge du cortege pour les personnes hypersensibles', pourquoi: 'Note : il vaut mieux integrer cette zone au cortege que creer un groupe separe, pour eviter l\'exclusion.', sections: ['manif'] },
    ],
};

const ETATS_LABELS = {
    'non':      'Non prevu',
    'prevu':    'Prevu',
    'commande': 'Commande / en cours',
    'confirme': 'Confirme',
    'na':       null,
    '':         null,
};
